import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { prepare, validateConfig, projectRoot } from './project-config.mjs';
const example = JSON.parse(fs.readFileSync(path.join(projectRoot, 'config', 'wechatagent.example.json'), 'utf8'));
validateConfig(example);
assert.deepEqual(example.wechat.whitelist, { groups: [], private: [] });
assert.throws(() => validateConfig({ ...example, ports: { ...example.ports, onebot: example.ports.weflow } }), /distinct/);
assert.throws(() => validateConfig({ ...example, persona: { default: '../bad' } }), /persona/);
assert.throws(() => validateConfig({ ...example, hook: { ...example.hook, baseUrl: 'http://0.0.0.0:30001' } }), /loopback/);
assert.throws(() => validateConfig({ ...example, hook: { ...example.hook, expectedVersion: '4.1.15.13' } }), /matching/);
const fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'WeChatAgent portable '));
try {
  fs.mkdirSync(path.join(fixture, 'config')); fs.mkdirSync(path.join(fixture, 'roles'));
  fs.copyFileSync(path.join(projectRoot, 'config', 'wechatagent.example.json'), path.join(fixture, 'config', 'wechatagent.example.json'));
  fs.writeFileSync(path.join(fixture, 'roles', `${example.persona.default}.md`), '# Test role');
  prepare(fixture);
  const bridge = JSON.parse(fs.readFileSync(path.join(fixture, 'state', 'bridge-config.json'), 'utf8'));
  const io = JSON.parse(fs.readFileSync(path.join(fixture, 'state', 'wechat-io-config.json'), 'utf8'));
  assert.equal(bridge.role, '# Test role');
  assert.equal(bridge.message_buffer.path, path.join(fixture, 'state', 'social-messages.json'));
  assert.equal(io.onebot_ws_url, `ws://127.0.0.1:${example.ports.onebot}/ws`);
  assert.equal(bridge.dsh_plugin.url, `http://127.0.0.1:${example.ports.dshPlugin}`);
  const token = fs.readFileSync(path.join(fixture, 'state', 'social-dsh-token.txt'), 'utf8');
  prepare(fixture); assert.equal(fs.readFileSync(path.join(fixture, 'state', 'social-dsh-token.txt'), 'utf8'), token);
  assert(!JSON.stringify(example).includes(token));
  const settingsFile = path.join(fixture, 'state', 'weflow', 'WeFlow-config.json');
  const settings = JSON.stringify({ httpApiPort: 22222, httpApiHost: 'custom-host', decryptKey: 'fixture-encrypted-key' });
  fs.writeFileSync(settingsFile, settings);
  const configFile = path.join(fixture, 'config', 'wechatagent.json');
  const config = JSON.parse(fs.readFileSync(configFile, 'utf8'));
  prepare(fixture);
  assert.equal(fs.readFileSync(settingsFile, 'utf8'), settings, 'database configuration must remain untouched');
  assert.equal(JSON.parse(fs.readFileSync(path.join(fixture, 'state', 'wechat-io-config.json'), 'utf8')).reader_token, io.reader_token);
  assert.throws(() => validateConfig({ ...config, runtime: { ...config.runtime, sender: 'uia' } }), /removed/);
} finally { fs.rmSync(fixture, { recursive: true, force: true }); }
for (const file of ['components/qq-bridge/src/social-bridge.js','packages/dsh-social-bridge-plugin/index.js','components/qq-bridge/LICENSE','components/weflow-cli/LICENSE','components/weflow-cli/scripts/nt_decrypt.py','components/weflow-cli/scripts/nt_common.py']) assert(fs.existsSync(path.join(projectRoot, file)), `Missing source/license: ${file}`);
console.log('Project config, portable paths, shared token preservation, and component completeness checks passed.');
